### ISSUE TITLE
hi ,could you like to  share me with the demo? i have seen the metric.by ,but no demo.py? how to u use the trained mode in generating 2048points for 1024 points?

### ISSUE THREAD

**Issue by AmyWan** [val-iisc/3d-lmnet#3] opened 2018-12-04 08:55 UTC

**Comment by priyankamandikal** [comment] 2018-12-06 13:02
Hello,

If you check the bash script in scripts/demo_lm.sh, you will see that it runs metrics.py with the argument '--visualize'. You will be able to visualize the results using metrics.py itself if you set this flag.

Regarding your second question, the network currently predicts 2048 points, and we have provided ground truth data for it. Only during evaluation we sample 1024 points from the predicted output so as to be comparable to other methods. We have provided ground truth data for 1024 points as well.

**Comment by AmyWan** [comment] 2018-12-08 10:55
> Hello,
> 
> If you check the bash script in scripts/demo_lm.sh, you will see that it runs metrics.py with the argument '--visualize'. You will be able to visualize the results using metrics.py itself if you set this flag.
> 
> Regarding your second question, the network currently predicts 2048 points, and we have provided ground truth data for it. Only during evaluation we sample 1024 points from the predicted output so as to be comparable to other methods. We have provided ground truth data for 1024 points as well.
yes,I have show the 2048 points.and your demo is for evaluation.I have another question:how to use the pix3d dataset in your net,the code is for the image in cad .?hope to reply ,thanks.

**Comment by AmyWan** [comment] 2018-12-17 09:33
when I use the real data in Pix3D,I cropped the imge with the size 128*128，using img_mask to extract the object in compex blackground.The result I produce is bad,Could u like to share me with yours?

**Comment by AmyWan** [comment] 2018-12-18 13:14
could you like to tell me the detailes to applay the net in real world image

**Comment by priyankamandikal** [comment] 2019-01-17 13:19
Original question has a response here: https://github.com/val-iisc/3d-lmnet/issues/3#issuecomment-444863530
Follow-up question is a duplicate of https://github.com/val-iisc/3d-lmnet/issues/4.

**Closed as completed by priyankamandikal** 2019-01-17 13:19 UTC
